### ISSUE TITLE
compile what?

### ISSUE THREAD

**Issue by PatWie** [fqnchina/CEILNet#2]
> compile the computeEdge.lua, ComputeXGrad.lua, ComputeYGrad.lua and L1Criterion.lua under the nn module

Can you please provide more information for stupid TensorFlow users like me?
[The docs](http://torch.ch/docs/developer-docs.html) are somewhat not helpful.

I get

```
th evaluation_reflection.lua
/home/user/torch/install/bin/luajit: /home/user/torch/install/share/lua/5.1/torch/File.lua:343: unknown Torch class <nn.ComputeXGrad>
stack traceback:

```

**Comment by fqnchina** [comment]
The lua files have to be put in /torch/extra/nn module directory, and editing init.lua file to include the corresponding file. Finally run the command under nn directory, luarocks make ./rocks/nn-scm-1.rockspec. Then nn module will be independently compiled.

The above steps should work it out.

**Comment by PatWie** [comment]
Thanks
